name: ds-general
channels:
  - conda-forge
  - nodefaults
dependencies:
  # Core
  - python = 3.11.*
  - jupyterlab
  # Data analysis
  - numpy
  - scipy
  - pandas
  - polars
  - pyarrow
  # Modelling
  - scikit-learn
  - statsmodels
  - category_encoders
  - xgboost
  - catboost
  - shap
  # Visualisation
  - matplotlib
  - seaborn
  - tabulate
  # Testing and code quality
  - pytest
  - black
  - ruff
  - isort
  # Tools and utilities
  - pip
  - requests
  - keyring
  - python-dotenv
  - nbdime
